---

- name: Lauch AWS Infrastructure
  hosts: localhost
  connection: local
  gather_facts: False


## Provide variable files
  vars_files:
    - vars/aws-credentials.yml
    - vars/specs.yml

  tasks:

  - name: Create security group
    ec2_group:
      ec2_access_key: "{{ user_access_key }}"
      ec2_secret_key: "{{ user_secret_key }}"
      name: test-security-group
      description: "A Security group"
      region: "{{ ec2_region }}"
      rules:
        - proto: tcp
          type: ssh
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
    register: basic_firewall


  - name: Create EC-2 instance
    ec2:
      ec2_access_key: "{{ user_access_key }}"
      ec2_secret_key: "{{ user_secret_key }}"
      region: "{{ ec2_region }}"
      group_id: "{{ basic_firewall.group_id }}"   
      instance_type: "{{ instance_type }}"
      image: "{{ ami_id }}"
      key_name: "{{ key_name }}"
      instance_tags:
            Name: test
      exact_count: 1
      count_tag:
            Name: test
      wait: true
    register: ec2

  ## Adding ip of created vms to hosts file
  - name: Add all instance public IPs to host group
    add_host: hostname={{ item.public_ip }} groups=ec2hosts
    with_items: ec2.instances


- name: Configure the instance
  hosts: ec2hosts  
  user: ec2-user
  gather_facts: true

  tasks:

  - name: Check NTP service
    service: name=ntpd state=started