#+Title: Wordpress Cloud Deployment Project
#+Author: Yogesh Agrawal
#+Email: yogeshiiith@gmail.com
#+Date: <2016-06-14 Tue>

* Introduction
  This document describes requirement, specifications and evaluation
  of the cloud deployment project.

* Project Description
  A blogging application in Wordpress is to be deployed on the AWS
  cloud. The application and the computer where application is running
  is to be continuously monitored. Technology to be used are
  centralised logging and dashboarding using the ELK (ElasticSearch,
  Logstash, Kibana) stack. The entire infrastructure is intended to be
  a container based system.  

* Requirements
  In order to achieve the above, we would need to:

  1. Create a Docker compose based ELK setup, so that it's repeatable
     and demonstrable on a development machine.
  2. Use Ansible for provisioning the minimal AWS infrastructure to
     run the ELK based logging infrastructure.
  3. Deploy dockerized WordPress based blogging application.
  4. Monitor the AWS resources and the blogging application using you
     ELK based centralised logging and monitoring infrastructure.
  5. Demonstrate your knowledge and understanding by preparing an
     insightful dashboard of your choice.

  Use the official WordPress Docker image to run a web application and
  monitor it using the centralised logging setup that is built above.

* Specifications
  - OS: Ubuntu Server 14.04 64-bit
  - App Server: Gunicorn/Nginx
  - Python: 2.7
  - Ansible
  - Docker 1.10
  - Wordpress official Docker image
    https://hub.docker.com/_/wordpress/
  - ElasticSearch
  - Logstash
  - Kibana

  In developing the solution, use GitHub/BitBucket and try to keep a
  decent commit history of how you approached the project.

* Deliverables
  A Git repo with
  1. the Ansible playbook,
  2. Dockerfiles and Docker compose files
  3. shell script(s)
     - Launch the AWS infrastructure with EC2 servers.
     - Begin the configuration management / bootstrapping of the
       server using Ansible.
     - Deploy the ELK stack.
     - Finally start the blogging app as a Docker process.
   DO NOT CHECK THIS INTO GITHUB WITH AWS KEYS.

* Evaluation
  After completion of the project - review of the approach taken would
  be reviewed and demo session will be there. In the demo session,
  demonstrate the solution and explain the steps taken to achieve the
  solution.
