wordpress:
 build: wordpress/
 container_name: wordpress
 ports:
   - "8081:80"
 log_driver: syslog
 log_opt:
   syslog-address: "tcp://logstash:25826"
 links:
   - db:mysql
 external_links:
   - logstash

db:
 build: mysql/
 container_name: db
 environment:
   MYSQL_ROOT_PASSWORD: example
